/* USER REDUCER TYPES */
export const SET_AUTHENTICATED = "SET_AUTHENTICATED";
export const SET_UNAUTHENTICATED = "SET_UNAUTHENTICATED";
export const SET_USER = "SET_USER";
export const LOADING_USER = "LOADING_USER";

/* UI REDUCER TYPES */
export const SET_ERRORS = "SET_ERRORS";
export const LOADING_UI = "LOADING_UI";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const STOP_LOADING_UI = "STOP_LOADING_UI";
export const SET_DASHBOARD = "SET_DASHBOARD";
export const SET_ERRORS_RENT = "SENT_ERRORS_RENT";

/* DATA REDUCER TYPES */
export const SET_SELECTED_USER = "SET_SELECTED_USER";
export const SET_USERS = "SET_USERS";
export const LOADING_DATA = "LOADING_DATA";
export const SET_VEHICLE = "SET_VEHICLE";
export const SET_VEHICLES = "SET_VEHICLES";
export const SET_EQUIPMENT = "SET_EQUIPMENT";
export const SET_TIMES = "SET_TIMES";
//export const INCREMENT_EQUIPMENT = "INCREMENT_EQUIPMENT";
//export const DECREMENT_EQUIPMENT = "DECREMENT_EQUIPMENT";
